[package]
name = "kitsune-spoofer"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
crossterm = "0.29.0"
dialoguer = "0.11.0"
get_if_addrs = "0.5.3"
ipconfig = "0.3.2"
is_elevated = "0.1.2"
rand = "0.9.2"

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"
